{
  "formatVersion": "1.1",
  "component": {
    "group": "com.softcircle.cardwidget",
    "module": "cardwidget-client",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.softcircle.cardwidget",
          "module": "cardwidget-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "cardwidget-client-0.1.0.aar",
          "url": "cardwidget-client-0.1.0.aar",
          "size": 42788,
          "sha512": "3a23e6b5b978dc1f74bfccf0ac8f1dd2bff7ce332b48229354d3cd8abc922ba732549e5477b8c6291aaf412b44925d6e3b4fef15d62148703fd079228e83e8a8",
          "sha256": "f002e27c440061adf75bcca5ac0abf8fda1b5ee092977c333fb80b3611ccde8f",
          "sha1": "899953298e7600cf79774f78eabf23bfa6599a2b",
          "md5": "55b77e0fbced8b0b87c22336fa03ad2b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.softcircle.cardwidget",
          "module": "cardwidget-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "cardwidget-client-0.1.0.aar",
          "url": "cardwidget-client-0.1.0.aar",
          "size": 42788,
          "sha512": "3a23e6b5b978dc1f74bfccf0ac8f1dd2bff7ce332b48229354d3cd8abc922ba732549e5477b8c6291aaf412b44925d6e3b4fef15d62148703fd079228e83e8a8",
          "sha256": "f002e27c440061adf75bcca5ac0abf8fda1b5ee092977c333fb80b3611ccde8f",
          "sha1": "899953298e7600cf79774f78eabf23bfa6599a2b",
          "md5": "55b77e0fbced8b0b87c22336fa03ad2b"
        }
      ]
    }
  ]
}
